/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./app/**/*.{js,jsx}",
    "./src/**/*.{js,jsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#c8c6c2",
        "surface-tint": "#e3c285",
        "on-surface": "#e5e2e1",
        "on-primary-fixed": "#261900",
        "on-tertiary-fixed": "#1c1b1b",
        "surface-bright": "#3a3939",
        "on-secondary": "#30312d",
        "outline-variant": "#4d463a",
        "tertiary-container": "#afadac",
        "on-error-container": "#ffdad6",
        "on-primary-fixed-variant": "#594312",
        "surface-container-high": "#2a2a2a",
        "on-secondary-container": "#b6b5b0",
        "outline": "#998f81",
        "surface-variant": "#353534",
        "tertiary-fixed-dim": "#c8c6c5",
        "surface-container-low": "#1c1b1b",
        "on-surface-variant": "#d0c5b5",
        "surface-dim": "#131313",
        "inverse-primary": "#735b28",
        "secondary-container": "#474743",
        "tertiary-fixed": "#e5e2e1",
        "primary": "#e5c487",
        "on-primary": "#402d00",
        "tertiary": "#cbc8c8",
        "error-container": "#93000a",
        "primary-fixed-dim": "#e3c285",
        "primary-container": "#c8a96e",
        "inverse-on-surface": "#313030",
        "secondary-fixed": "#e4e2dd",
        "surface-container-lowest": "#0e0e0e",
        "on-background": "#e5e2e1",
        "surface-container-highest": "#353534",
        "background": "#131313",
        "on-tertiary-container": "#424141",
        "secondary": "#c8c6c2",
        "on-secondary-fixed-variant": "#474743",
        "on-secondary-fixed": "#1b1c19",
        "primary-fixed": "#ffdea3",
        "on-tertiary": "#313030",
        "error": "#ffb4ab",
        "on-primary-container": "#533d0c",
        "surface": "#131313",
        "on-error": "#690005",
        "on-tertiary-fixed-variant": "#474646",
        "inverse-surface": "#e5e2e1",
        "surface-container": "#201f1f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "8px",
        "section-gap": "120px",
        gutter: "32px",
        "margin-mobile": "20px",
        "container-max": "1120px",
        "margin-desktop": "80px",
      },
      fontFamily: {
        "display-lg": ["Playfair Display", "serif"],
        "label-caps": ["DM Sans", "sans-serif"],
        "headline-lg-mobile": ["Playfair Display", "serif"],
        "headline-md": ["Playfair Display", "serif"],
        "pull-quote": ["Playfair Display", "serif"],
        "headline-lg": ["Playfair Display", "serif"],
        "body-lg": ["DM Sans", "sans-serif"],
        "body-md": ["DM Sans", "sans-serif"],
      },
      fontSize: {
        "display-lg": ["72px", { lineHeight: "1.1", letterSpacing: "-0.02em", fontWeight: "600" }],
        "label-caps": ["12px", { lineHeight: "1.0", letterSpacing: "0.15em", fontWeight: "700" }],
        "headline-lg-mobile": ["32px", { lineHeight: "1.2", fontWeight: "500" }],
        "headline-md": ["32px", { lineHeight: "1.3", fontWeight: "500" }],
        "pull-quote": ["36px", { lineHeight: "1.4", fontWeight: "400" }],
        "headline-lg": ["48px", { lineHeight: "1.2", fontWeight: "500" }],
        "body-lg": ["18px", { lineHeight: "1.7", fontWeight: "400" }],
        "body-md": ["16px", { lineHeight: "1.6", fontWeight: "400" }],
      },
    },
  },
  plugins: [],
}
